version: '3'

services:
  alipay.demo.pcpayment:
    image: alipaydemopcpayment:v1
    container_name: alipaydpcpayment
    build:
      container_name: alipaydpcpayment
      context: .
      dockerfile: Alipay.Demo.PCPayment/Dockerfile
